imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            path:      "%kernel.logs_dir%/%kernel.environment%.log"
            type:      rotating_file
            level:     debug
            max_files: 30
        nested:
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            type:  stream
            level: debug
        console:
            type:  console
