imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata.yml }
    - { resource: media.yml }

# Framework
framework:
    translator:      { fallbacks: [ "%locale%" ] }
    secret:          "%secret%"
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: [ "twig" ]
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "SonataCoreBundle:Form:datepicker.html.twig"
    globals:
        google_analytics_enabled: %google_analytics_enabled%
        google_analytics_account: "%google_analytics_account%"
        project_title:            "%project_web_title%"
        admin_tag_version:        "v1.3.8"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    java:           "%assetic_path_java%"
    node:           "%assetic_path_node%"
    use_controller: false
    filters:
        cssrewrite: ~
        less:
            node:       "%assetic_path_node%"
            node_paths: [ "%assetic_path_node_modules%" ]
    assets:
        mycss:
            inputs:
#                - "@AppBundle/Resources/public/css/main.less"
                - "@AppBundle/Resources/public/css/icomoon.less"
        myjs:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"

# Doctrine
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy:             doctrine.orm.naming_strategy.underscore
        auto_mapping:                true

doctrine_migrations:
    dir_name:  "%kernel.root_dir%/../src/AppBundle/DoctrineMigrations"
    namespace: AppBundle\DoctrineMigrations

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   true
            sortable:       false
            tree:           false

# Swiftmailer
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     AppBundle\Entity\User
    group:
        group_class:   AppBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# JMS i18n Routing
jms_i18n_routing:
    default_locale: "%locale%"
    locales:        %locale_i18n_full%
    strategy:       prefix

# A2lix Translations
a2lix_translation_form:
    locales:          %locale_i18n%
    default_required: true
    manager_registry: doctrine
    templating:       "::A2lix/i18n_form_template.html.twig"

# TinyMCE
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: "%locale%"
    theme:
        simple:
            theme: "modern"
            plugins:
                - "advlist autolink lists link charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime nonbreaking save contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "bold italic underline | bullist numlist outdent indent | link"
            image_advtab: true

# Payum
payum:
    security:
        token_storage:
            AppBundle\Entity\Cart\PaymentToken: { doctrine: orm }
    storages:
        AppBundle\Entity\Cart\Payment: { doctrine: orm }
    gateways:
        offline:
            factory: offline
        paypal:
            factory:   paypal_express_checkout
            username:  "%paypal_username%"
            password:  "%paypal_password%"
            signature: "%paypal_signature%"
            sandbox:   "%paypal_sandbox%"
