security:
    acl:
        connection: default
    role_hierarchy:
        ROLE_SONATA_CMS:
            - ROLE_ADMIN_CONTACTMESSAGE_LIST
            - ROLE_ADMIN_CONTACTMESSAGE_VIEW
            - ROLE_ADMIN_CONTACTMESSAGE_CREATE
            - ROLE_ADMIN_CONTACTMESSAGE_EDIT
            - ROLE_ADMIN_CONTACTMESSAGE_DELETE
            - ROLE_ADMIN_CONTACTMESSAGE_EXPORT
            - ROLE_ADMIN_WORKCATEGORY_LIST
            - ROLE_ADMIN_WORKCATEGORY_VIEW
            - ROLE_ADMIN_WORKCATEGORY_CREATE
            - ROLE_ADMIN_WORKCATEGORY_EDIT
            - ROLE_ADMIN_WORKCATEGORY_DELETE
            - ROLE_ADMIN_WORKCATEGORY_EXPORT
            - ROLE_ADMIN_WORK_LIST
            - ROLE_ADMIN_WORK_VIEW
            - ROLE_ADMIN_WORK_CREATE
            - ROLE_ADMIN_WORK_EDIT
            - ROLE_ADMIN_WORK_DELETE
            - ROLE_ADMIN_WORK_EXPORT
            - ROLE_ADMIN_WORKIMAGE_LIST
            - ROLE_ADMIN_WORKIMAGE_VIEW
            - ROLE_ADMIN_WORKIMAGE_CREATE
            - ROLE_ADMIN_WORKIMAGE_EDIT
            - ROLE_ADMIN_WORKIMAGE_DELETE
            - ROLE_ADMIN_WORKIMAGE_EXPORT
            - ROLE_ADMIN_SLIDERIMAGE_LIST
            - ROLE_ADMIN_SLIDERIMAGE_VIEW
            - ROLE_ADMIN_SLIDERIMAGE_CREATE
            - ROLE_ADMIN_SLIDERIMAGE_EDIT
            - ROLE_ADMIN_SLIDERIMAGE_DELETE
            - ROLE_ADMIN_SLIDERIMAGE_EXPORT
            - ROLE_ADMIN_PRODUCT_LIST
            - ROLE_ADMIN_PRODUCT_VIEW
            - ROLE_ADMIN_PRODUCT_CREATE
            - ROLE_ADMIN_PRODUCT_EDIT
            - ROLE_ADMIN_PRODUCT_DELETE
            - ROLE_ADMIN_PRODUCT_EXPORT
            - ROLE_ADMIN_PRODUCTIMAGE_LIST
            - ROLE_ADMIN_PRODUCTIMAGE_VIEW
            - ROLE_ADMIN_PRODUCTIMAGE_CREATE
            - ROLE_ADMIN_PRODUCTIMAGE_EDIT
            - ROLE_ADMIN_PRODUCTIMAGE_DELETE
            - ROLE_ADMIN_PRODUCTIMAGE_EXPORT
            - ROLE_ADMIN_CART_LIST
            - ROLE_ADMIN_CART_VIEW
            - ROLE_ADMIN_CART_CREATE
            - ROLE_ADMIN_CART_EDIT
            - ROLE_ADMIN_CART_DELETE
            - ROLE_ADMIN_CART_EXPORT
            - ROLE_ADMIN_CUSTOMER_LIST
            - ROLE_ADMIN_CUSTOMER_VIEW
            - ROLE_ADMIN_CUSTOMER_CREATE
            - ROLE_ADMIN_CUSTOMER_EDIT
            - ROLE_ADMIN_CUSTOMER_DELETE
            - ROLE_ADMIN_CUSTOMER_EXPORT
        ROLE_SONATA_MANAGER:
            - ROLE_ADMIN_USER_LIST
            - ROLE_ADMIN_USER_VIEW
            - ROLE_ADMIN_USER_CREATE
            - ROLE_ADMIN_USER_EDIT
            - ROLE_ADMIN_USER_DELETE
            - ROLE_ADMIN_USER_EXPORT
        ROLE_CMS:
            - ROLE_USER
            - ROLE_SONATA_CMS
            - ROLE_SONATA_ADMIN
        ROLE_ADMIN:
            - ROLE_CMS
            - ROLE_SONATA_MANAGER
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    access_decision_manager:
        strategy: unanimous
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: /admin(.*)
            context: user
            form_login:
                provider:                       fos_userbundle
                login_path:                     /admin/login
                use_forward:                    false
                check_path:                     /admin/login_check
                failure_path:                   /admin/login
                default_target_path:            /admin/dashboard
                always_use_default_target_path: true
                use_referer:                    true
            logout:
                path:   /admin/logout
                target: /admin/login
            anonymous: true
        development:
            pattern: ^/secure(.*)
            context: user
            anonymous: true
        frontend:
            pattern: ^/(.*)
            context: user
            anonymous: true
    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/secure/, role: ROLE_USER }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
