services:
# Sonata Admins
    admin.work:
        class: AppBundle\Admin\WorkAdmin
        arguments: [ ~, AppBundle\Entity\Work, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Work", group: "Works" }
    admin.workcategory:
        class: AppBundle\Admin\WorkCategoryAdmin
        arguments: [ ~, AppBundle\Entity\WorkCategory, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Category", group: "Works" }
    admin.workimage:
        class: AppBundle\Admin\WorkImageAdmin
        arguments: [ ~, AppBundle\Entity\WorkImage, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Image", group: "Works" }
    admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [ ~, AppBundle\Entity\Product, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Product", group: "Products" }
