# Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.user.block.menu:         ~
        sonata.block.service.text:      ~
        sonata.admin.block.admin_list:  ~
        admin.block.messages:           ~

# Admin
sonata_admin:
    title: "%project_web_title%"
    title_logo: "/bundles/app/images/backend-favicon.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: "::Admin/layout.html.twig"
        show:   "::Admin/show.html.twig"
    dashboard:
        groups:
            Treballs:
                icon: "<i class='fa fa-briefcase'></i>"
            Productes:
                icon: "<i class='fa fa-table'></i>"
            Sliders:
                icon: "<i class='fa fa-picture-o'></i>"
            Contactes:
                icon: "<i class='fa fa-envelope'></i>"
            Botiga:
                icon: "<i class='fa fa-shopping-cart'></i>"
            Usuaris:
                icon: "<i class='fa fa-user'></i>"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <h1 style="margin-top:0">CMS web Hidràulica</h1>
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ Treballs, Productes, Sliders ]
            -
                position: right
                type: admin.block.messages
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ Contactes, Botiga, Usuaris ]
            -
                position: bottom
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <div><hr style="margin-top:40px;border-top:solid 1px #d2d6de"><p><i class="fa fa-info-circle"></i> Suport tècnic aquí: <a href="mailto:suport@flux.cat?subject=Hidraulica CMS help" style="color:#000">suport@flux.cat</a></p></div>

# User
sonata_user:
    security_acl: true
    manager_type: orm
